import {
  AlertTriangle,
  ArrowLeftRight,
  BadgeCheck,
  BarChart3,
  Boxes,
  Calendar,
  Clock3,
  Film,
  Gem,
  Headphones,
  Image as ImageIcon,
  LayoutDashboard,
  Package,
  Plus,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Tag,
  Target,
  TrendingUp,
  Truck,
  User,
  Users,
  Warehouse,
  Wand2,
  Inbox,
  RotateCcw,
} from "lucide-react";

export const NAV_ICONS = {
  layout: LayoutDashboard,
  image: ImageIcon,
  film: Film,
  sparkles: Sparkles,
  users: Users,
  bag: ShoppingBag,
  plus: Plus,
  tag: Tag,
  boxes: Boxes,
  swap: ArrowLeftRight,
  truck: Truck,
  alert: AlertTriangle,
  inbox: Inbox,
  sliders: SlidersHorizontal,
  warehouse: Warehouse,
  package: Package,
  undo: RotateCcw,
  headset: Headphones,
  wand: Wand2,
  calendar: Calendar,
  gem: Gem,
  trend: TrendingUp,
  team: Users,
  chart: BarChart3,
  badge: BadgeCheck,
  target: Target,
  clock: Clock3,
  user: User,
};

export const navIcon = (name) => NAV_ICONS[name] ?? LayoutDashboard;
