import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Plus, Search, Archive, Eye, Pencil, Images } from "lucide-react";
import AdminPage from "../../components/admin/AdminPage";
import AdminPanel from "../../components/admin/AdminPanel";
import { AtelierButton } from "../../design-system";
import repo,{catalogMetrics} from "../../services/catalogRepository";
import { useProductCovers, useProductMediaSummaries } from "../../hooks/useMedia";

const money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`;
export default function AdminProducts(){
 const [items,setItems]=useState(repo.all); const [q,setQ]=useState(""); const [status,setStatus]=useState("ALL");
 const refresh=()=>setItems(repo.all()); useEffect(()=>{window.addEventListener("pratikshya-products-changed",refresh);return()=>window.removeEventListener("pratikshya-products-changed",refresh)},[]);
 const withCovers=useProductCovers(items); const filtered=useMemo(()=>withCovers.filter(p=>(!q||[p.name,p.sku,p.category,p.subcategory,p.brand,p.fabric,p.collection].join(" ").toLowerCase().includes(q.toLowerCase()))&&(status==="ALL"||p.status===status)),[withCovers,q,status]); const m=catalogMetrics(items); const mediaSummaries=useProductMediaSummaries(filtered);
 return <AdminPage eyebrow="Business / Products" title="Product catalog" description="Manage the products presented across PRATIKSHYA FASHON." actions={<AtelierButton as={Link} to="/admin/products/new" size="chip"><Plus size={14}/> Add product</AtelierButton>}>
 <div className="grid grid-cols-2 gap-3 mb-6 md:grid-cols-6">{[["Total",m.total],["Published",m.published],["Drafts",m.drafts],["Featured",m.featured],["Low stock",m.lowStock],["Out of stock",m.out]].map(([a,b])=><div className="border border-mist bg-white p-4" key={a}><p className="font-ui text-[10px] uppercase tracking-widest text-taupe">{a}</p><strong className="font-display text-2xl font-light">{b}</strong></div>)}</div>
 <AdminPanel eyebrow="Catalog" title="Products"><div className="flex flex-col gap-3 mb-5 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-taupe" size={15}/><input aria-label="Search products" className="w-full border border-mist py-2.5 pl-9 pr-3 font-ui text-sm" placeholder="Search name, SKU, category, fabric…" value={q} onChange={e=>setQ(e.target.value)}/></label><select className="border border-mist px-3 font-ui text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>PUBLISHED</option><option>DRAFT</option><option>ARCHIVED</option></select></div>
 <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-mist font-ui text-[10px] uppercase tracking-widest text-taupe">{["Product","SKU","Category","Price","Stock","Media","Status","Actions"].map(x=><th className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(p=><tr className="border-b border-mist/60 font-ui text-sm" key={p.id}><td className="px-3 py-4"><div className="flex items-center gap-3"><img src={p.image} alt="" className="h-12 w-10 object-cover"/><span>{p.name}</span></div></td><td className="px-3 text-taupe">{p.sku}</td><td className="px-3">{p.category}</td><td className="px-3">{money(p.price)}</td><td className="px-3">{p.stock||0}</td><td className="px-3">{(()=>{const s=mediaSummaries[p.id];if(!s||s.isEmpty)return <Link to={`/admin/products/${p.id}/media`} className="font-ui text-[11px] uppercase tracking-widest text-taupe underline-offset-4 hover:text-accent hover:underline">Add media</Link>;return <Link to={`/admin/products/${p.id}/media`} className="flex flex-col gap-0.5 underline-offset-4 hover:text-accent hover:underline"><span className="font-ui text-[11px] text-ink">{s.images} img · {s.videos} vid</span>{s.needsCover&&<span className="font-ui text-[10px] uppercase tracking-widest text-accent">Needs cover</span>}</Link>;})()}</td><td className="px-3"><span className="rounded-full bg-mist px-2 py-1 text-[10px]">{p.status}</span></td><td className="px-3"><div className="flex gap-2"><Link to={`/admin/products/${p.id}/edit`} aria-label="Edit"><Pencil size={15}/></Link><Link to={`/admin/products/${p.id}`} aria-label="View"><Eye size={15}/></Link><Link to={`/admin/products/${p.id}/media`} aria-label={`Manage media for ${p.name}`}><Images size={15}/></Link><button aria-label="Archive" onClick={()=>repo.updateStatus(p.id,"ARCHIVED")}><Archive size={15}/></button></div></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="py-12 text-center font-ui text-sm text-taupe">No products match your current filters.</p>}</AdminPanel></AdminPage>;
}
